backend:
  name: git-gateway
  branch: master

# display_url: 
# logo_url: 
public_folder: '/images'
media_folder: 'source/images'
# media_library:
#   name: uploadcare
#   config:
    # publicKey: 

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page one'
        name: 'one'
        file: 'pages/one.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Slug', name: 'slug', widget: 'hidden', default: 'one'}
          - {label: 'Tags', name: 'tag', widget: 'hidden', default: 'nav'}
          - {label: 'Summary', name: 'summary', hint: 'Will be displayed as a larger text', widget: 'text'}
          - {label: 'Body', name: 'body', widget: 'markdown'}