backend:
  name: git-gateway
  branch: master
display_url: https://yero.netlify.com/
logo_url: https://yero.netlify.com/assets/favicons/android-chrome-384x384.png
public_folder: '/images'
media_folder: 'source/images'
media_library:
  name: uploadcare
  config:
    publicKey: 007a43026cafa8857be4

collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page one'
        name: 'one'
        file: 'pages/one.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Slug', name: 'slug', widget: 'hidden', default: 'one'}
          - {label: 'Tags', name: 'tag', widget: 'hidden', default: 'nav'}
          - {label: 'Summary', name: 'summary', hint: 'Will be displayed as a larger text', widget: 'text'}
          - {label: 'Body', name: 'body', widget: 'markdown'}
     
      - label: 'FAQ'
        name: 'faq'
        file: 'pages/faq.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Slug', name: 'slug', widget: 'hidden', default: 'one'}
          - {label: 'Tags', name: 'tag', widget: 'hidden', default: 'nav'}
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'faq'}  
          - label: 'question'
            name: 'question'
            widget: 'list'
            fields:
              - {label: 'Question', name: 'question', widget: 'string'}
              - {label: 'Answer', name : 'answer',widget: 'text'}

              
  - name: 'settings'
    label: 'Settings'
    delete: false
    editor:
      preview: false
    files:
      - label: 'Site Settings'
        name: 'settings'
        file: 'config/config.json'
        fields:
          - label: 'General'
            name: 'site'
            widget: 'object'
            fields:
              - { label: 'Site Name', name: 'name', widget: 'string' }
              - { label: 'Language', name: 'lang', widget: 'string' }
              - { label: 'Default Title', name: 'title', widget: 'string' }
              - { label: 'Home URL', name: 'url', widget: 'string', hint: 'Must starts with https://' }
              - { label: 'Theme Color', name: 'themeColor', widget: 'string', hint: 'Hex value of a color. For example, #ffffff' }

  - name: 'events'
    label: 'Events'
    editor:
      preview: false
    folder: 'events'
    create: true
    slug: '{{slug}}'
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Date', name: 'date', widget: 'date'}
      - {label: 'location', name: 'location',widget: 'string'}
      - {label: 'Image', name: 'image', widget: 'image', required: false}
      - {label: 'Body', name: 'body', widget: 'markdown'}   
        label: 'Tags' 
        name :  'tags'
        widget: 'list'
        hint: "coma separeted values and must include'event' for example event,food ,sport"
      - {label: 'Body', name: 'body', widget: 'markdown'}      
      