backend:
  name: git-gateway
  branch: master

 display_url: 'https://yero.netlify.com/'
 logo_url: https://yero.netlify.com/assets/favicons/android-chrome-384x384.png
public_folder: '/images'
media_folder: 'source/images'
 media_library:
  name: uploadcare
  config:
  publicKey: 
007a43026cafa8857be4



collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'Page one'
        name: 'one'
        file: 'pages/one.md'
        fields:
          - {label: 'Title', name: 'title', widget: 'string'}
          - {label: 'Slug', name: 'slug', widget: 'hidden', default: 'one'}
          - {label: 'Tags', name: 'tag', widget: 'hidden', default: 'nav'}
          - {label: 'Summary', name: 'summary', hint: 'Will be displayed as a larger text', widget: 'text'}
          - {label: 'Body', name: 'body', widget: 'markdown'}